name: CI

on: [push, pull_request]

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: cluster tests
      run: ./runtest-cluster


  test-32bit:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get update && sudo apt-get install libc6-dev-i386
        make 32bit
    - name: test
      run: |
        sudo apt-get install tcl8.5
    - name: cluster tests
      run: ./runtest-cluster

  test-tls:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make BUILD_TLS=yes
    - name: test
      run: |
        sudo apt-get install tcl8.5 tcl-tls
        ./utils/gen-test-certs.sh
    - name: cluster tests
      run: ./runtest-cluster

