name: Daily

on:
  pull_request:
    branches:
      # any PR to a release branch.
      - '[0-9].[0-9]'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      valgrind:
        description: 'with valgrind'
        required: true
        default: 'true'
      tls:
        description: 'with tls'
        required: true
        default: 'true'
      iothreads:
        description: 'with io threads'
        required: true
        default: 'true'
      freebsd:
        description: 'with freebsd'
        required: true
        default: 'true'
      cluster:
        description: 'with cluster tests'
        required: true
        default: 'true'
      sentinel:
        description: 'with sentinel tests'
        required: true
        default: 'true'
      arguments:
        description: 'extra arguments'
        required: true
        default: ''

jobs:

  test-ubuntu-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}
    - name: unittest
      run: ./src/redis-server test all

  test-ubuntu-libc-malloc:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}

  test-ubuntu-no-malloc-usable-size:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc CFLAGS=-DNO_MALLOC_USABLE_SIZE
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}

  test-ubuntu-32bit:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get update && sudo apt-get install libc6-dev-i386
        make 32bit REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: |
        make -C tests/modules 32bit # the script below doesn't have an argument, we must build manually ahead of time
        ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}
    - name: unittest
      run: ./src/redis-server test all

  test-ubuntu-tls:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    if: github.event.inputs.tls != 'false'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make BUILD_TLS=yes
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx tcl-tls
        ./utils/gen-test-certs.sh
        ./runtest --accurate --verbose --tls --dump-logs ${{github.event.inputs.arguments}}
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: |
        ./runtest-moduleapi --verbose --tls ${{github.event.inputs.arguments}}
        ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: |
        ./runtest-sentinel --tls ${{github.event.inputs.arguments}}
        ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: |
        ./runtest-cluster --tls ${{github.event.inputs.arguments}}
        ./runtest-cluster ${{github.event.inputs.arguments}}

  test-ubuntu-io-threads:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    if: github.event.inputs.iothreads != 'false'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx tcl-tls
        ./runtest --config io-threads 4 --config io-threads-do-reads yes --accurate --verbose --tags network --dump-logs ${{github.event.inputs.arguments}}
    - name: cluster tests
      run: |
        ./runtest-cluster --config io-threads 4 --config io-threads-do-reads yes ${{github.event.inputs.arguments}}

  test-valgrind:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    if: github.event.inputs.valgrind != 'false'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make valgrind REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: test
      run: |
        sudo apt-get update
        sudo apt-get install tcl8.6 tclx valgrind -y
        ./runtest --valgrind --verbose --clients 1 --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --valgrind --no-latency --verbose --clients 1 ${{github.event.inputs.arguments}}
    - name: unittest
      run: |
        valgrind --track-origins=yes --suppressions=./src/valgrind.sup --show-reachable=no --show-possibly-lost=no --leak-check=full --log-file=err.txt ./src/redis-server test all
        if grep -q 0x err.txt; then cat err.txt; exit 1; fi

  test-valgrind-no-malloc-usable-size:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    if: github.event.inputs.valgrind != 'false'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make valgrind CFLAGS="-DNO_MALLOC_USABLE_SIZE"
    - name: test
      run: |
        sudo apt-get update
        sudo apt-get install tcl8.6 tclx valgrind -y
        ./runtest --valgrind --verbose --clients 1 --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --valgrind --no-latency --verbose --clients 1 ${{github.event.inputs.arguments}}

  test-centos7-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install gcc make
        make
    - name: test
      run: |
        yum -y install which tcl tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}

  test-centos7-tls:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    if: github.event.inputs.tls != 'false'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install centos-release-scl epel-release
        yum -y install devtoolset-7 openssl-devel openssl
        scl enable devtoolset-7 "make BUILD_TLS=yes"
    - name: test
      run: |
        yum -y install tcl tcltls tclx
        ./utils/gen-test-certs.sh
        ./runtest --accurate --verbose --tls --dump-logs ${{github.event.inputs.arguments}}
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: |
        ./runtest-moduleapi --verbose --tls ${{github.event.inputs.arguments}}
        ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      if: github.event.inputs.sentinel != 'false'
      run: |
        ./runtest-sentinel --tls ${{github.event.inputs.arguments}}
        ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: |
        ./runtest-cluster --tls ${{github.event.inputs.arguments}}
        ./runtest-cluster ${{github.event.inputs.arguments}}

  test-macos-latest:
    runs-on: macos-latest
    if: github.repository == 'oranagra/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: |
        ./runtest --accurate --verbose --no-latency --dump-log ${{github.event.inputs.arguments}}s
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}

  test-freebsd:
    runs-on: macos-latest
    if: github.repository == 'oranagra/redis'
    if: github.event.inputs.freebsd != 'false'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: test
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        sync: rsync
        prepare: pkg install -y bash gmake lang/tcl86 lang/tclx
        run: >
          gmake &&
          ./runtest --accurate --verbose --no-latency --dump-logs ${{github.event.inputs.arguments}} &&
          MAKE=gmake ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}} &&
          if [ ${{github.event.inputs.sentinel}} == 'true' ] ; then ./runtest-sentinel ${{github.event.inputs.arguments}} ; fi &&
          if [ ${{github.event.inputs.cluster}} == 'true' ] ; then ./runtest-cluster ${{github.event.inputs.arguments}} ; fi

  test-alpine-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          apk add build-base
          make REDIS_CFLAGS='-Werror'
    - name: test
      run: |
        apk add tcl procps tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}

  test-alpine-libc-malloc:
    runs-on: ubuntu-latest
    if: github.repository == 'oranagra/redis'
    container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          apk add build-base
          make REDIS_CFLAGS='-Werror' USE_JEMALLOC=no CFLAGS=-DUSE_MALLOC_USABLE_SIZE
    - name: test
      run: |
        apk add tcl procps tclx
        ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.arguments}}
    - name: module api test
      run: ./runtest-moduleapi --verbose ${{github.event.inputs.arguments}}
    - name: sentinel tests
      run: ./runtest-sentinel ${{github.event.inputs.arguments}}
    - name: cluster tests
      if: github.event.inputs.cluster != 'false'
      run: ./runtest-cluster ${{github.event.inputs.arguments}}
